# Generated by Django 5.2.8 on 2025-11-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'about'), ('index', 'index'), ('services', 'services')], max_length=150)),
                ('image', models.ImageField(upload_to='about/')),
                ('intitulé', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('blog', 'blog'), ('about', 'about'), ('contact', 'Contact'), ('gallery', 'gallery'), ('pricing', 'pricing'), ('team', 'team'), ('service-detail', 'service-detail')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='banner3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('single-blog-post-rightsidebar', 'single-blog-post-rightsidebar'), ('single-blog-post-leftsidebar', 'single-blog-post-leftsidebar'), ('single-blog-post-withoutsidebar', 'single-blog-post-withoutsidebar')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=155)),
                ('resolution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('description1', models.CharField(max_length=120)),
                ('description2', models.CharField(max_length=120)),
                ('lien', models.URLField(blank=True, max_length=225, null=True)),
                ('mot_lien', models.CharField(max_length=120)),
            ],
        ),
    ]
