# Generated by Django 5.2.8 on 2025-11-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32, verbose_name='Nom de la page')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32, verbose_name='Nom de la section')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(verbose_name='Ordre dans la page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page', verbose_name='Page hôte')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.section', verbose_name='Section incluse')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('page', 'ordre'), ('page', 'section')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(related_name='pages', through='website.PageSection', to='website.section'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32, verbose_name='Nom de la menu')),
                ('url', models.CharField(max_length=255, verbose_name='URL de la menu')),
                ('ordre', models.IntegerField(verbose_name='Ordre de la menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.menu', verbose_name='Parent menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['ordre'],
                'unique_together': {('parent', 'ordre')},
            },
        ),
    ]
