# Generated by Django 5.2.8 on 2025-11-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_page_section_pagesection_page_sections_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'À propos', 'verbose_name_plural': 'À propos'},
        ),
        migrations.AddField(
            model_name='about',
            name='section_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('blog', 'blog'), ('about', 'about'), ('contact', 'Contact'), ('gallery', 'gallery'), ('pricing', 'pricing'), ('team', 'team'), ('service-detail', 'service-detail'), ('services', 'services'), ('index', 'index')], max_length=50),
        ),
    ]
