# Generated by Django 5.2.8 on 2025-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_service_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(default='START SHIPPING WITH US', max_length=200, verbose_name='Sous-titre')),
                ('titre_principal', models.TextField(default='We are covering all logistics solutions for you', verbose_name='Titre principal')),
                ('description', models.TextField(default="Whatever item needs to be delivered or shipped, we're capable to do that!", verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Section Services (En-tête)',
                'verbose_name_plural': 'Section Services (En-tête)',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
