# Generated by Django 5.2.8 on 2025-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_sectionservices_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(max_length=200, verbose_name='Sous-titre')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('page', models.CharField(default='index', max_length=50, verbose_name='Page')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'En-tête Services',
                'verbose_name_plural': 'En-têtes Services',
                'ordering': ['page', '-date_modification'],
            },
        ),
        migrations.DeleteModel(
            name='SectionServices',
        ),
        migrations.AddField(
            model_name='services',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='services',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
