# Generated by Django 5.2.8 on 2025-12-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_serviceheader_delete_sectionservices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceheader',
            options={},
        ),
        migrations.RemoveField(
            model_name='serviceheader',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='serviceheader',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='serviceheader',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='serviceheader',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serviceheader',
            name='sous_titre',
        ),
        migrations.RemoveField(
            model_name='serviceheader',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='services',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='big_title',
            field=models.CharField(default='We are covering all logistics solutions for you', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='small_title',
            field=models.CharField(default='START SHIPPING WITH US', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceheader',
            name='page',
            field=models.CharField(default='index', max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
