# Generated by Django 5.2.8 on 2025-12-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='index', max_length=50)),
                ('small_title', models.CharField(max_length=200)),
                ('big_title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='features/')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('feature_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.featureheader')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
