# Generated by Django 5.2.8 on 2025-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_featureheader_featureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_items/'),
        ),
    ]
